### ISSUE TITLE
Try the api

### ISSUE THREAD

**Issue by onno-timmerman** [QuangPhamll/nuxtjs_wagtail#1]
If you try to run the following you will get an error. Something to do with the html_path and host...
connect ECONNREFUSED 127.0.0.1:7999   

```
 asyncData({app, route}) {
      const path = route.path
      console.log(path)
      return app.$axios.$get(`http://localhost:7999/api/v2/pages/find/?html_path=${path}`)
        .then((res) => {
          return {server: res}
        })
    },
```

**Comment by QuangPhamll** [comment]
Tks @onno-timmerman 
i have merged a PR for api backend communication: https://github.com/QuangPhamll/nuxtjs_wagtail/commit/6ea52890a653810a1c05020bbc1ada1fcd6553a6

The url `http://localhost:7999` work only in `process.client` of Nuxt . In this projet I have 2 services frontend and backend in a docker-compose file so in case of process.server, frontend server nodejs and backend is created in a internal network of docker and in this network they don't understand `http://localhost:7999`
Tks for you feed back, i will try to find a better solution for api communication.

**Comment by QuangPhamll** [comment]
@onno-timmerman 
fix problem of host client and host server in https://github.com/QuangPhamll/nuxtjs_wagtail/commit/226fbbc2f3bc9a638bc1f7ace6943b080b706a9b
Get api from backend with nuxtjs plugin `~/plugins/axios` not only `axios`:

```
import axios from '~/plugins/axios'
....
const {data} = await axios.get('/api/v2/pages/?slug=home');
....
```
